### PR TITLE
Bump mockito and regenerate mocks

### PR DESCRIPTION
**Pull request by srawlins**
The existing mock files contain a dangerous `Future.value` call, where, for a potentially non-nullable type `S`, we call `Future<S>.value(null)`. But `S` may be non-nullable, so this is dangerous. The dart analyzer will start reporting this. See https://github.com/dart-lang/sdk/issues/53253. See [this issue](https://github.com/flutter/flutter/issues/137294) in Flutter for a reference to the fixes made in Flutter.

This PR just bumps mockito, and regenerates the mocks, where it starts generating safer code. For an example, see in the diff on line 487 in the old copy. (I wish the diff were more isolated, but import prefixes changed and it looks like some other things.)

### CODE REVIEW

**Comment by srawlins** [comment]
Ping, this is blocking a fix for https://github.com/dart-lang/sdk/issues/53253.

**Comment by Goddchen** [comment]
Looks like the newly generated code produces some issues with the analyzer and the tests. Let me have a look.

**Comment by Goddchen** [comment]
Seems like somehow it won't compile with mockito 5.4.0, but needs at least 5.4.2, I guess. Not sure why the CI job says `mockito 5.4.0 (5.4.3 available)` and is not using mockito 5.4.3 (pubspec.lock is not part of the repo, so it should download the latest versions). Any ideas?

**Comment by Goddchen** [comment]
If you simply upgrade the dependency from `mockito: ^5.4.0` to `mockito: ^5.4.3`, that would fix the issues.

**Comment by srawlins** [comment]
Sorry about that! Thanks for following up and digging into that. I've bumped it.

**Comment by Goddchen** [comment]
`Because dart_rfb depends on mockito >=5.4.1 which requires SDK version >=2.19.0 <4.0.0, version solving failed.`

Welcome to dependency hell... I guess it's fine if we update the required dart SDK version to `>=2.19.0`. Upgrade it in `pubspec.yaml` and in the GitHub Actions files.

**Comment by srawlins** [comment]
OK, done! Thanks!

**Comment by Goddchen** [comment]
`Because dart_rfb depends on mockito >=5.4.3 which requires SDK version ^3.1.0, version solving failed.`.

Like I said, dependency hell... Can you upgrade it to `^3.1.0`?

**Comment by Goddchen** [comment]
And maybe just run `dart analyze` this time locally before pushing your commit, to save us some time 😉

**Comment by srawlins** [comment]
Sorry about the back-and-forth. I don't have a copy of Dart 2.19.0 or earlier so wouldn't have caught that issue. But it analyzes cleanly with Dart 3.2.3 🤷

**Review by Goddchen — APPROVED** [review]
LGTM, ty!

**Comment by srawlins** [comment]
Thanks a million for your patience 🙏

**Pull request merged**
